services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
    env_file:
      - .env
    environment:
      - HF_ENDPOINT=https://huggingface.co
      - HF_HUB_CACHE=/hf_cache
      - TRANSFORMERS_CACHE=/hf_cache
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - HF_HUB_OFFLINE=0
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - hf_cache:/hf_cache
      - hf_models:/root/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    depends_on:
      - product_search

  product_search:
    build:
      context: ./product_search_service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - URL=http://localhost:8000/openapi.json
    ports:
      - "8002:8080"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

volumes:
  hf_cache:
  hf_models: