services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
    env_file:
      - .env
    environment:
      - HF_ENDPOINT=https://huggingface.co
      - HF_HUB_CACHE=/hf_cache
      - TRANSFORMERS_CACHE=/hf_cache
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - HF_HUB_OFFLINE=0
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - hf_cache:/hf_cache
      - hf_models:/root/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - URL=http://localhost:8000/openapi.json
    ports:
      - "8001:8080"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

  vllm:
    build:
      context: .
      dockerfile: Dockerfile.vllm
    env_file:
      - .env
    ports:
      - "8002:8002"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 120s
      timeout: 60s
      retries: 10
      start_period: 600s

volumes:
  hf_cache:
  hf_models: